### PR TITLE
chore: improvements for types

### PR DESCRIPTION
**Pull request by KFlash**
This PR improves the overall performance for type parsing and removes some duplicate code.

### CODE REVIEW

**Comment by KFlash** [comment]
@aladdin-add One quick question. Do we need to make a node for `|` a `&`?  I don't think it's needed to catch the comments in cases like `| a`  because we can get the comments from start pos of the `type` , but for cases like

```ts
| 

//  foo
a

&

b 
```

how would we do it here? Wr don't  have the end value of the `|` so I can see how we can grab a comments? The comment is an detached comment and not a leading of `a`.  

How do we solve this?

**Comment by KFlash** [comment]
Thinking about this again... I think the current changes is enough to catch the edge cases. For series of either unions or intersection nodes or both we can just do a `node.start + 1` to get correct pos. Doing it differently result in lots of redundant location values and larger CST that consumes bytes.

**Review by aladdin-add — APPROVED** [review]

**Comment by KFlash** [comment]
@aladdin-add My biggest issue with Kataw is that I have to think like 10 devs. Not only one :) And I have memorized every single code line. This things consumes lots of energy and time :)

**Comment by KFlash** [comment]
@aladdin-add Can you merge this PR and re-generate the snapshots?

**Pull request merged**
