### PR TITLE
chore: refactor printer

### PR DESCRIPTION
**Pull request by KFlash**

### CODE REVIEW

**Comment by KFlash** [comment]
@aladdin-add I added a few tests now to show you what's going on. Look at the tests, and then look at the printed output!

**Comment by KFlash** [comment]
@aladdin-add Added a few more tests you can study! I cracked the secret comment code, so everything works

**Comment by KFlash** [comment]
@aladdin-add I test everything while doing this refactoring. I first do a parse, then I transform the code, use the visitor and print the returned output before I parse the printed output to catch errors.

**Comment by KFlash** [comment]
@aladdin-add Take a look at the tests I just pushed. They are generated with the new printer. No pretty printing **yet**, but a 24 hours marathon is over and everything works except for a few adjustments. 

The returned code is correct, and the comments are 100% correct. Feel free to compare with Prettier 👍

**Comment by aladdin-add** [comment]
conflicts need to be resolved.

**Comment by KFlash** [comment]
No rush with the conflicts. Easy to do a force push from master ?

**Comment by KFlash** [comment]
@aladdin-add Still *wip* but it's printing types now ;)

**Comment by KFlash** [comment]
@aladdin-add Look at the latest push. Nearly done now. Can you do a force push to this branch to solve conflicts?
I'm soon to start another 24 hours non-stop marathon to finish of this. There are known issues in Kataw types that I need to fix.

**Comment by KFlash** [comment]
@aladdin-add Can you overwrite this tests with the tests from master branch?

**Comment by KFlash** [comment]
Closing as no action done by @aladdin-add and it will be super seeded

**Pull request closed without merging**
