### PR TITLE
chore: implements hints

### PR DESCRIPTION
**Pull request by KFlash**
This PR implements hints. Diagnostics that will give a friendly hint about best practice and the best way to write JS code.

This is not related to linting.

### CODE REVIEW

**Review by aladdin-add — APPROVED** [review]
LGTM!

**Comment by aladdin-add** [comment]
simply curious what's difference hint vs. lint.

**Comment by KFlash** [comment]
Good question! Linting tells you if there are issues in the code etc. Idea with a "hint" tell you better way to write your code. See the attached test

**Comment by KFlash** [comment]
Closing this for now

**Pull request closed without merging**
