### PR TITLE
chore: WIP! fixes #20

### LINKED ISSUE #20: investigate loc pos for all nodes
Looks like some node start / end values are off by 1.  

This is not critical. The start / end values are only for internal usage and will only affect comment attachments.

### PR DESCRIPTION
**Pull request by KFlash**
This fixes #20 and also simplifies the AST so it consumes less bytes.

### CODE REVIEW

**Comment by KFlash** [comment]
@aladdin-add Can you check if anything gives you an 'undefined' ?

**Comment by KFlash** [comment]
@aladdin-add Some of this changes fixes our printer issues for arrows. 

This case: 'x => y;'

Now we can do:

```js
if (node.nodeFlags & NodeFlags.NoneParenthesizedArrow) {
      return printBindingIdentifier()
}

// None parenthesized arrows

```

**Review by aladdin-add — APPROVED** [review]
LGTM! 💯

**Comment by KFlash** [comment]
@aladdin-add I'm merging this now. I will open another PR for loc tracking on types

**Pull request merged**
