### PR TITLE
testing ci

### PR DESCRIPTION
**Pull request by aladdin-add**

### CODE REVIEW

**Comment by KFlash** [comment]
@aladdin-add DO NOT merge "the beast" code to master. It's far from complete and comment does not work.

**Comment by aladdin-add** [comment]
simply curious why "you change the 'tob.ts' file again"?

it was working on my local (and the ci). maybe another windows issue? have you config your ide to `unix-style` linebreak.

**Comment by KFlash** [comment]
I changed the "tob.ts" so it could use the "/printer3" pretty printer code instead of the printer that exist on Kataw.

**Comment by KFlash** [comment]
The tests pass locally. Not sure why they fail now. There are no differences between the printers either except that "the beast" is almost identical to Prettier, but with improved formatting. And some smart format functionality.

**Comment by aladdin-add** [comment]
the tests passed; the ci was failing as linting issues.

**Comment by KFlash** [comment]
Linting issues is the last thing to fix and this printer is far from complete :)

**Comment by aladdin-add** [comment]
closing as the ci is working as expected. you can open a new PR once it's done.

**Pull request closed without merging**
