### PR TITLE
chore: rename "Hybrid CST" => "CST"

### PR DESCRIPTION
**Pull request by aladdin-add**

### CODE REVIEW

**Comment by aladdin-add** [comment]
I think you just need to review this commit: :) 

https://github.com/kataw/kataw/pull/70/commits/4fc9cf19b1e87e8cf09efa28b09911a3a7e3fd07

**Review by KFlash — APPROVED** [review]

**Comment by KFlash** [comment]
Looks okay. Does the printer options work?

**Comment by aladdin-add** [comment]
no. it is a todo:
https://github.com/kataw/kataw/blob/f3eabdad351f10ebb4180ebcc46c3f71389d42dd/test/runner/tob.ts#L81-L89

**Comment by KFlash** [comment]
okay. The printer is actually working. I only adjusting it now and fixing perf and comments

**Pull request merged**
