### PR TITLE
testing windows

### PR DESCRIPTION
**Pull request by aladdin-add**

### CODE REVIEW

**Comment by KFlash** [comment]
All tests pas, but ehh

dunno

**Comment by KFlash** [comment]
All tests passing, but ehh

notpass

**Comment by aladdin-add** [comment]
macos and ubuntu was working as expected, and updated 0 tests.

seems windows has a smaller limits. (⓿_⓿)
you know how to higher the limit??

**Comment by KFlash** [comment]
Nope but I tried too google "(node:5712) UnhandledPromiseRejectionWarning: windows 10"

More errors to come on windows after this is fixed :)

**Comment by KFlash** [comment]
Use this code on top of `utils.ts`. It will solve the issue. Soon as it's fixed, you need to fix the infinite loop that will be the next issue to solve 👍 

```ts
import * as aladdin from 'fs';
var gracefulFs = require('graceful-fs')
gracefulFs.gracefulify(aladdin)
```

**Comment by KFlash** [comment]
Maybe better to refactor the runner to avoid using promises?

**Comment by KFlash** [comment]
@aladdin-add I have no more time to investigate now, but I know what happend, but not where!  If empty .md file the update works just fine, but if I try to update that .md file again it will somehow "slice" the entire .md file and get that content and mix it up with the new content and write it to file.

**Comment by aladdin-add** [comment]
I did repro your issue. 

image

let's be consistent in line breaks. 2 options:
* config your ide to unix style
* I can update all the files to windows style

**Comment by aladdin-add** [comment]
fixed by e13e097dd5c737563f16428e637d28ad0419f4eb

**Comment by KFlash** [comment]
Yes. That's one of my issues ;)  The other is that it take existing conext and mixed with new and write to file

**Pull request closed without merging**
