### PR TITLE
chore: add enum constants

### PR DESCRIPTION
**Pull request by KFlash**

### CODE REVIEW

**Comment by KFlash** [comment]
@aladdin-add Is this easier for you to read?

**Comment by KFlash** [comment]
@aladdin-add If you change any of the '0' with '1' etc in the constants I'm sure you will run into OOM and lots of broken tests :)

How to prevent this?

**Review by aladdin-add — APPROVED** [review]
LGTM! 💯

**Comment by aladdin-add** [comment]
just do not change?

**Pull request merged**
